// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dk_batch_ridge_positive_cpp
Rcpp::List dk_batch_ridge_positive_cpp(const arma::mat& y, const arma::mat& scores, const Rcpp::IntegerVector& query_gene, const Rcpp::IntegerVector& query_cell, const double ridge, const int min_target_observed, const bool support_adaptive_rank, const double bias_kappa);
RcppExport SEXP _DropoutKiller_dk_batch_ridge_positive_cpp(SEXP ySEXP, SEXP scoresSEXP, SEXP query_geneSEXP, SEXP query_cellSEXP, SEXP ridgeSEXP, SEXP min_target_observedSEXP, SEXP support_adaptive_rankSEXP, SEXP bias_kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_gene(query_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_cell(query_cellSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type min_target_observed(min_target_observedSEXP);
    Rcpp::traits::input_parameter< const bool >::type support_adaptive_rank(support_adaptive_rankSEXP);
    Rcpp::traits::input_parameter< const double >::type bias_kappa(bias_kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_batch_ridge_positive_cpp(y, scores, query_gene, query_cell, ridge, min_target_observed, support_adaptive_rank, bias_kappa));
    return rcpp_result_gen;
END_RCPP
}
// dk_batch_tree_ridge_positive_cpp
Rcpp::List dk_batch_tree_ridge_positive_cpp(const arma::mat& y, const arma::mat& local_mean, const arma::mat& local_variance, const arma::mat& effective_n, const arma::mat& W, const arma::mat& scores, const Rcpp::IntegerVector& query_gene, const Rcpp::IntegerVector& query_cell, const double ridge, const int min_target_observed, const double min_effective_donors, const double local_info_kappa, const bool support_adaptive_rank);
RcppExport SEXP _DropoutKiller_dk_batch_tree_ridge_positive_cpp(SEXP ySEXP, SEXP local_meanSEXP, SEXP local_varianceSEXP, SEXP effective_nSEXP, SEXP WSEXP, SEXP scoresSEXP, SEXP query_geneSEXP, SEXP query_cellSEXP, SEXP ridgeSEXP, SEXP min_target_observedSEXP, SEXP min_effective_donorsSEXP, SEXP local_info_kappaSEXP, SEXP support_adaptive_rankSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type local_mean(local_meanSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type local_variance(local_varianceSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type effective_n(effective_nSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type W(WSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_gene(query_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_cell(query_cellSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type min_target_observed(min_target_observedSEXP);
    Rcpp::traits::input_parameter< const double >::type min_effective_donors(min_effective_donorsSEXP);
    Rcpp::traits::input_parameter< const double >::type local_info_kappa(local_info_kappaSEXP);
    Rcpp::traits::input_parameter< const bool >::type support_adaptive_rank(support_adaptive_rankSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_batch_tree_ridge_positive_cpp(y, local_mean, local_variance, effective_n, W, scores, query_gene, query_cell, ridge, min_target_observed, min_effective_donors, local_info_kappa, support_adaptive_rank));
    return rcpp_result_gen;
END_RCPP
}
// dk_batch_p1_state_cpp
Rcpp::List dk_batch_p1_state_cpp(const arma::mat& y, const arma::mat& scores, const double ridge, const int min_target_observed, const bool support_adaptive_rank, const double bias_kappa);
RcppExport SEXP _DropoutKiller_dk_batch_p1_state_cpp(SEXP ySEXP, SEXP scoresSEXP, SEXP ridgeSEXP, SEXP min_target_observedSEXP, SEXP support_adaptive_rankSEXP, SEXP bias_kappaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type scores(scoresSEXP);
    Rcpp::traits::input_parameter< const double >::type ridge(ridgeSEXP);
    Rcpp::traits::input_parameter< const int >::type min_target_observed(min_target_observedSEXP);
    Rcpp::traits::input_parameter< const bool >::type support_adaptive_rank(support_adaptive_rankSEXP);
    Rcpp::traits::input_parameter< const double >::type bias_kappa(bias_kappaSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_batch_p1_state_cpp(y, scores, ridge, min_target_observed, support_adaptive_rank, bias_kappa));
    return rcpp_result_gen;
END_RCPP
}
// dk_simplex_weights_cpp
arma::mat dk_simplex_weights_cpp(const arma::mat& cell_gram, const Rcpp::IntegerVector& query_index, const Rcpp::IntegerMatrix& candidate_index, const arma::mat& geometry_prior, const double lambda, const double prune_weight, const double tol);
RcppExport SEXP _DropoutKiller_dk_simplex_weights_cpp(SEXP cell_gramSEXP, SEXP query_indexSEXP, SEXP candidate_indexSEXP, SEXP geometry_priorSEXP, SEXP lambdaSEXP, SEXP prune_weightSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type cell_gram(cell_gramSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_index(query_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type candidate_index(candidate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type geometry_prior(geometry_priorSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type prune_weight(prune_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_simplex_weights_cpp(cell_gram, query_index, candidate_index, geometry_prior, lambda, prune_weight, tol));
    return rcpp_result_gen;
END_RCPP
}
// dk_simplex_cell_weights_cpp
Rcpp::List dk_simplex_cell_weights_cpp(const arma::mat& features, const Rcpp::LogicalMatrix& query_observed, const Rcpp::IntegerVector& query_index, const Rcpp::IntegerMatrix& candidate_index, const arma::mat& geometry_prior, const int reliable_features, const double lambda, const double prune_weight, const double tol);
RcppExport SEXP _DropoutKiller_dk_simplex_cell_weights_cpp(SEXP featuresSEXP, SEXP query_observedSEXP, SEXP query_indexSEXP, SEXP candidate_indexSEXP, SEXP geometry_priorSEXP, SEXP reliable_featuresSEXP, SEXP lambdaSEXP, SEXP prune_weightSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type features(featuresSEXP);
    Rcpp::traits::input_parameter< const Rcpp::LogicalMatrix& >::type query_observed(query_observedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type query_index(query_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type candidate_index(candidate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type geometry_prior(geometry_priorSEXP);
    Rcpp::traits::input_parameter< const int >::type reliable_features(reliable_featuresSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type prune_weight(prune_weightSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_simplex_cell_weights_cpp(features, query_observed, query_index, candidate_index, geometry_prior, reliable_features, lambda, prune_weight, tol));
    return rcpp_result_gen;
END_RCPP
}
// dk_simplex_predict_events_cpp
Rcpp::List dk_simplex_predict_events_cpp(const arma::sp_mat& x, const Rcpp::IntegerVector& event_gene, const Rcpp::IntegerVector& event_cell, const Rcpp::IntegerMatrix& candidate_index, const arma::mat& cell_weights, const double positive_mass_tol);
RcppExport SEXP _DropoutKiller_dk_simplex_predict_events_cpp(SEXP xSEXP, SEXP event_geneSEXP, SEXP event_cellSEXP, SEXP candidate_indexSEXP, SEXP cell_weightsSEXP, SEXP positive_mass_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::sp_mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_gene(event_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type event_cell(event_cellSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type candidate_index(candidate_indexSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type cell_weights(cell_weightsSEXP);
    Rcpp::traits::input_parameter< const double >::type positive_mass_tol(positive_mass_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(dk_simplex_predict_events_cpp(x, event_gene, event_cell, candidate_index, cell_weights, positive_mass_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DropoutKiller_dk_batch_ridge_positive_cpp", (DL_FUNC) &_DropoutKiller_dk_batch_ridge_positive_cpp, 8},
    {"_DropoutKiller_dk_batch_tree_ridge_positive_cpp", (DL_FUNC) &_DropoutKiller_dk_batch_tree_ridge_positive_cpp, 13},
    {"_DropoutKiller_dk_batch_p1_state_cpp", (DL_FUNC) &_DropoutKiller_dk_batch_p1_state_cpp, 6},
    {"_DropoutKiller_dk_simplex_weights_cpp", (DL_FUNC) &_DropoutKiller_dk_simplex_weights_cpp, 7},
    {"_DropoutKiller_dk_simplex_cell_weights_cpp", (DL_FUNC) &_DropoutKiller_dk_simplex_cell_weights_cpp, 9},
    {"_DropoutKiller_dk_simplex_predict_events_cpp", (DL_FUNC) &_DropoutKiller_dk_simplex_predict_events_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DropoutKiller(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
