# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dk_batch_ridge_positive_cpp <- function(y, scores, query_gene, query_cell, ridge, min_target_observed, support_adaptive_rank, bias_kappa) {
    .Call(`_DropoutKiller_dk_batch_ridge_positive_cpp`, y, scores, query_gene, query_cell, ridge, min_target_observed, support_adaptive_rank, bias_kappa)
}

dk_batch_tree_ridge_positive_cpp <- function(y, local_mean, local_variance, effective_n, W, scores, query_gene, query_cell, ridge, min_target_observed, min_effective_donors, local_info_kappa, support_adaptive_rank) {
    .Call(`_DropoutKiller_dk_batch_tree_ridge_positive_cpp`, y, local_mean, local_variance, effective_n, W, scores, query_gene, query_cell, ridge, min_target_observed, min_effective_donors, local_info_kappa, support_adaptive_rank)
}

dk_batch_p1_state_cpp <- function(y, scores, ridge, min_target_observed, support_adaptive_rank, bias_kappa) {
    .Call(`_DropoutKiller_dk_batch_p1_state_cpp`, y, scores, ridge, min_target_observed, support_adaptive_rank, bias_kappa)
}

dk_simplex_weights_cpp <- function(cell_gram, query_index, candidate_index, geometry_prior, lambda, prune_weight, tol = 1e-10) {
    .Call(`_DropoutKiller_dk_simplex_weights_cpp`, cell_gram, query_index, candidate_index, geometry_prior, lambda, prune_weight, tol)
}

dk_simplex_cell_weights_cpp <- function(features, query_observed, query_index, candidate_index, geometry_prior, reliable_features, lambda, prune_weight, tol = 1e-10) {
    .Call(`_DropoutKiller_dk_simplex_cell_weights_cpp`, features, query_observed, query_index, candidate_index, geometry_prior, reliable_features, lambda, prune_weight, tol)
}

dk_simplex_predict_events_cpp <- function(x, event_gene, event_cell, candidate_index, cell_weights, positive_mass_tol = 1e-8) {
    .Call(`_DropoutKiller_dk_simplex_predict_events_cpp`, x, event_gene, event_cell, candidate_index, cell_weights, positive_mass_tol)
}
